// ============================================
// Supabase Reverse Proxy — Cloudflare Worker
// Generated by create-jiobase (https://jiobase.com)
// Bypasses ISP DNS blocking of *.supabase.co
//
// Features:
//   - Full HTTP proxy (REST, Auth, Storage, Functions, GraphQL)
//   - WebSocket relay (Supabase Realtime)
//   - CORS handling with configurable origins
//   - Service filtering
//   - Location header rewriting (preserves OAuth flows)
// ============================================

// --- Config ---
const SUPABASE_URL = "https://plllqgqkrxitquxkohos.supabase.co";
const ALLOWED_ORIGINS = "*";
const ENABLED_SERVICES: SupabaseService[] = ['rest', 'auth', 'storage', 'realtime', 'functions', 'graphql'];

// --- Types ---
type SupabaseService = 'rest' | 'auth' | 'storage' | 'realtime' | 'functions' | 'graphql';

const SERVICE_PATH_MAP: Record<string, SupabaseService> = {
  rest: 'rest',
  auth: 'auth',
  storage: 'storage',
  realtime: 'realtime',
  functions: 'functions',
  graphql: 'graphql',
};

// --- CORS ---

function isOriginAllowed(origin: string): boolean {
  if (ALLOWED_ORIGINS === '*') return true;
  const allowed = ALLOWED_ORIGINS.split(',').map((o) => o.trim());
  return allowed.includes(origin);
}

function handlePreflight(request: Request): Response {
  const origin = request.headers.get('Origin') || '*';
  const headers = new Headers();

  if (isOriginAllowed(origin)) {
    headers.set('Access-Control-Allow-Origin', origin);
    headers.set('Access-Control-Allow-Credentials', 'true');
    headers.set('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
    headers.set('Access-Control-Allow-Headers', request.headers.get('Access-Control-Request-Headers') || '*');
    headers.set('Access-Control-Max-Age', '86400');
  }

  return new Response(null, { status: 204, headers });
}

function addCorsHeaders(responseHeaders: Headers, request: Request): void {
  const origin = request.headers.get('Origin');
  if (origin && isOriginAllowed(origin)) {
    responseHeaders.set('Access-Control-Allow-Origin', origin);
    responseHeaders.set('Access-Control-Allow-Credentials', 'true');
    responseHeaders.set('Access-Control-Allow-Headers', request.headers.get('Access-Control-Request-Headers') || '*');
    responseHeaders.set('Access-Control-Allow-Methods', 'GET, POST, PUT, PATCH, DELETE, OPTIONS');
    responseHeaders.set('Access-Control-Expose-Headers', '*');
  }
}

// --- Service detection ---

function getServiceFromPath(pathname: string): SupabaseService | null {
  const match = pathname.match(/^\/([a-z]+)\//);
  if (!match) return null;
  return SERVICE_PATH_MAP[match[1]] || null;
}

// --- HTTP Proxy ---

async function handleHttpProxy(request: Request): Promise<Response> {
  const url = new URL(request.url);

  // Check if the service is enabled
  const service = getServiceFromPath(url.pathname);
  if (service && !ENABLED_SERVICES.includes(service)) {
    return Response.json(
      { error: `Service '${service}' is not enabled for this proxy` },
      { status: 403 },
    );
  }

  // Build upstream URL
  const upstreamUrl = new URL(SUPABASE_URL);
  upstreamUrl.pathname = url.pathname;
  upstreamUrl.search = url.search;

  // Clone headers, set upstream host
  const headers = new Headers(request.headers);
  headers.set('Host', upstreamUrl.hostname);
  headers.delete('cf-connecting-ip');
  headers.delete('cf-ray');
  headers.delete('cf-visitor');
  headers.delete('cf-ipcountry');

  // Forward request
  const upstreamResponse = await fetch(upstreamUrl.toString(), {
    method: request.method,
    headers,
    body: request.method !== 'GET' && request.method !== 'HEAD' ? request.body : undefined,
    redirect: 'manual',
  });

  // Clone response headers
  const responseHeaders = new Headers(upstreamResponse.headers);

  // Rewrite Location headers pointing to Supabase back to our proxy domain.
  // Only rewrite the host - NOT query params (preserves OAuth redirect_uri).
  const location = responseHeaders.get('Location');
  if (location) {
    try {
      const locUrl = new URL(location);
      const supabaseHost = new URL(SUPABASE_URL).hostname;
      if (locUrl.hostname === supabaseHost) {
        locUrl.hostname = url.hostname;
        responseHeaders.set('Location', locUrl.toString());
      }
    } catch {
      // Malformed Location header - leave as-is
    }
  }

  // Add CORS headers
  addCorsHeaders(responseHeaders, request);

  // Add proxy identifier
  responseHeaders.set('X-Proxied-By', 'JioBase');

  return new Response(upstreamResponse.body, {
    status: upstreamResponse.status,
    statusText: upstreamResponse.statusText,
    headers: responseHeaders,
  });
}

// --- WebSocket Relay (Supabase Realtime) ---

async function handleWebSocket(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const upstreamUrl = new URL(SUPABASE_URL);
  upstreamUrl.pathname = url.pathname;
  upstreamUrl.search = url.search;

  // CF Workers require https:// (not wss://) with Upgrade header for WebSocket
  const headers = new Headers(request.headers);
  headers.set('Host', upstreamUrl.hostname);
  headers.delete('cf-connecting-ip');
  headers.delete('cf-ray');
  headers.delete('cf-visitor');
  headers.delete('cf-ipcountry');

  const upstreamResp = await fetch(upstreamUrl.toString(), { headers });
  const upstreamWs = upstreamResp.webSocket;

  if (!upstreamWs) {
    return new Response('Failed to establish upstream WebSocket', { status: 502 });
  }
  upstreamWs.accept();

  // Create client WebSocket pair
  const [client, server] = Object.values(new WebSocketPair());
  server.accept();

  // Relay messages bidirectionally
  upstreamWs.addEventListener('message', (event) => {
    try { server.send(event.data); } catch {}
  });
  server.addEventListener('message', (event) => {
    try { upstreamWs.send(event.data); } catch {}
  });

  // Relay close events
  upstreamWs.addEventListener('close', (event) => {
    try { server.close(event.code, event.reason); } catch {}
  });
  server.addEventListener('close', (event) => {
    try { upstreamWs.close(event.code, event.reason); } catch {}
  });

  // Handle errors
  upstreamWs.addEventListener('error', () => {
    try { server.close(1011, 'Upstream error'); } catch {}
  });
  server.addEventListener('error', () => {
    try { upstreamWs.close(1011, 'Client error'); } catch {}
  });

  return new Response(null, { status: 101, webSocket: client });
}

// --- Main handler ---

export default {
  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    // Health check
    if (url.pathname === '/__health') {
      return Response.json({ status: 'ok', service: 'supabase-proxy' });
    }

    try {
      // CORS preflight
      if (request.method === 'OPTIONS') {
        return handlePreflight(request);
      }

      // WebSocket upgrade (Supabase Realtime)
      const upgradeHeader = request.headers.get('Upgrade');
      if (upgradeHeader && upgradeHeader.toLowerCase() === 'websocket') {
        return handleWebSocket(request);
      }

      // HTTP proxy
      return handleHttpProxy(request);
    } catch (err) {
      console.error('Proxy error:', err);
      return Response.json({ error: 'Internal proxy error' }, { status: 500 });
    }
  },
} satisfies ExportedHandler;
